# Generated by Django 4.0.2 on 2022-10-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_products',
            name='sp_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
