# Generated by Django 4.0.2 on 2022-10-18 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0002_alter_seller_products_sp_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_products',
            name='sp_name',
            field=models.CharField(choices=[('potato', 'Potato'), ('tomato', 'Tomato'), ('onion', 'Onion'), ('spinach', 'Spinach'), ('spring_onion', 'Spring Onion')], max_length=255),
        ),
    ]
