# Generated by Django 4.0.2 on 2022-10-18 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller_products', '0003_alter_seller_products_sp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_products',
            old_name='seller',
            new_name='seller_id',
        ),
    ]
