# Generated by Django 4.0.2 on 2022-10-20 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duties', '0001_initial'),
        ('orders', '0002_alter_ordermodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='duty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Duty', to='duties.dutymodel'),
        ),
    ]
